### PR TITLE
Initial PR to cover more features, starting with MQTT

### PR DESCRIPTION
**Pull request by anubisg1**
Added MQTT support and improved captive portal.

### CODE REVIEW

**Comment by anubisg1** [comment]
@ecodina  i'd like to see your feedback please.

Here i am did some code clean up, i added MQTT and adjusted the captive portal accordingly 

i know that i still need to add documentation.

For MQTT the topics are:

hunter/device_hostname/checkIn  --> will publish online/rebooted/reconnected/Dead Somewhere 
hunter/device_hostname/result  --> will publish the same result json as the reset api 
hunter/device_hostname/zone/XXX --> commands the zone with json payload to be published by the user ( {"action": "start","time": "1"}  -- {"action": "stop"}
hunter/device_hostname/program/XXX --> commands the zone with json payload to be published by the user ( {"action": "start"}


The captive portal will ask for the MQTT data too

**Comment by ecodina** [comment]
Hi @anubisg1 

Thank you for your work! I have a pretty tight deadline at the end of the month, so until then I won't be able to test it. I hope it is OK.

**Comment by anubisg1** [comment]
absolutely, that's not a problem!

**Comment by anubisg1** [comment]
creating a new PR from my repository, i messed up with git :)

**Pull request closed without merging**
