### PR TITLE
Initial PR to cover more features, starting with MQTT 

### PR DESCRIPTION
**Pull request by anubisg1**
Ecodina i'd like to see your feedback please.

Here i did some code clean up, i added MQTT and adjusted the captive portal accordingly

i know that i still need to add documentation.

For MQTT the topics are:

hunter/device_hostname/checkIn --> will publish online/rebooted/reconnected/Dead Somewhere
hunter/device_hostname/result --> will publish the same result json as the rest api
hunter/device_hostname/zone/XXX --> commands the zone with json payload to be published by the user ( {"action": "start","time": "1"} -- {"action": "stop"} )
hunter/device_hostname/program/XXX --> commands the zone with json payload to be published by the user ( {"action": "start"} )

The captive portal will ask for the MQTT data too

### CODE REVIEW

**Comment by anubisg1** [comment]
Also OTA support is added , and can be access by going to /update

**Review by ecodina — COMMENTED** [review]
Hi @anubisg1 !

I should start by saying that I am mainly a Java and Python developer, so I am learning as this project grows.

Thank you for your work. I have reviewed your code and it looks good to me (you have even added OTA updates!). I have also checked that it correctly builds.

I just have a few points:

1. I've seen that you have replaced the original configuration of platformio.ini. Since platformIO allows defining several environments, it may be better to use them and then select which one you wish to build by specifying "default_envs". The file would look like this:

```
[platformio]
default_envs = d1_mini

[env]
lib_deps = 
	knolleary/PubSubClient@^2.8
	me-no-dev/ESPAsyncTCP@^1.2.2
	me-no-dev/ESP Async WebServer@^1.2.3
	bblanchon/ArduinoJson@^6.18.4
	alanswx/ESPAsyncWiFiManager@^0.30

[env:d1_mini]
platform = espressif8266
board = d1
framework = arduino

[env:d1_mini_pro]
platform = espressif8266
framework = arduino
board = d1_mini_pro
```

2. I believe that, for the sake of organization, the definition of class MQTT should be in `MQTT.h` instead of `global_config.h`. The only change this would require is to add `#include <mqtt.h>` to `wifi.h`.

3. The method `handleRoot` in `ota.cpp` is unused. From what I've seen, its functionality is handled directly in method `setup_APIRoutes` of `web_server.cpp`.

4. Do not worry about the documentation yet. After the above points are fixed (or you provide feedback as why they should remain as they are) I will approve the pull request. Then I will add an issue to the project so that we don't forget to add it.

5. Since I come from a Python background, code formatting is important to me and I believe it helps to understand it. I've seen some lines that are not indented (or using 2 spaces instead of a TAB or 4 spaces as the rest of the code). However, don't worry about it, I will proceed as # 4.

Let me know what you think!

**Comment by anubisg1** [comment]
Hello @ecodina, thank you for your feedback.

I'll work all those points, they are reasonable.

1) I used platformio for the first time, so my bad, I'll fix that
2) I'll check that, shouldn't be a problem
3) ok, let me look at it
4)  agrees
5) I will scan through that, I haven't noticed it. If I find something I'll fix right away

Thank you

**Comment by anubisg1** [comment]
Hello Ecodina,

the above commits handle your requests:

[x] platformio env file
[x] mqtt class
[x] handleRoot 
[] documentation
[x] formatting (this is the only one i could quickly find)

**Comment by ecodina** [comment]
Thank you, @anubisg1 !

I have merged your pull request and closed it.

**Pull request merged**
