### PR TITLE
toggle mqtt in captive setup, save in config.json

### PR DESCRIPTION
**Pull request by ccmmgg**

### CODE REVIEW

**Comment by ccmmgg** [comment]
Screenshot showing the MQTT toggle:
 
Screenshot 2022-06-25 at 08 02 38

Also removed the esp stack trace decoder.py file I left in by mistake. Useful script from here: https://github.com/janLo/EspArduinoExceptionDecoder but shouldn't be included in your project.

**Comment by ecodina** [comment]
Great! I still hadn't merged the PR since when I was reviewing it, you pushed another commit so I wanted to make sure it was finished.

I must admit, I am not a fan of the format introduced in commit [228fd4d](https://github.com/ecodina/hunter-wifi/pull/20/commits/228fd4d6410d1b3096e2dec90ad7c12f2f28807f). Maybe it's due to my previous experience in Java, but to me it makes the code much more crowded and difficult to follow!

**Comment by ccmmgg** [comment]
> Great! I still hadn't merged the PR since when I was reviewing it, you pushed another commit so I wanted to make sure it was finished.
> 
> I must admit, I am not a fan of the format introduced in commit [228fd4d](https://github.com/ecodina/hunter-wifi/pull/20/commits/228fd4d6410d1b3096e2dec90ad7c12f2f28807f). Maybe it's due to my previous experience in Java, but to me it makes the code much more crowded and difficult to follow!

You telling me you don't want
```
YourFunction(
    calls,
    to,
    look
    like,
    this?,
          );
```
I used the default vscode format document. I'll spend some time making it more concise. I don't particularly like that style either. I'll drop a PR soon tuning up code formatting and I think pulling a local version of the pure css code so that the web interface can still look pretty without an internet connection might be in order. I'll see if it bloats up the littlefs image too much.

**Comment by ecodina** [comment]
It's just the bracket on the new line. However, since this is not a very big project, I don't want to enforce any coding style: just use what you're more comfortable with!

**Pull request merged**
